#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @File  : config.py
# @Author: shone
# @Date  : 2017/11/5
# @Desc
# import os

CSRF_ENABLED = True
SECRET_KEY = 'you-will-never-guess'

# mysql+pymysql://username:password@localhost/db_name
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://app:app@127.0.0.1:3306/flask_db?charset=utf8'
SQLALCHEMY_COMMIT_ON_TEARDOWN = True
SQLALCHEMY_TRACK_MODIFICATIONS = False

MAIL_DEBUG = True
MAIL_SUPPRESS_SEND = False
MAIL_SERVER = 'smtp.qq.com'
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USE_TLS = False
MAIL_USERNAME = '859633004@qq.com'
MAIL_PASSWORD = 'nekvciszyhfkbebd'
MAIL_DEFAULT_SENDER = '1595591337@qq.com'