"""initial migration

Revision ID: 282408d6d0f2
Revises: 
Create Date: 2017-11-17 12:01:28.240094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '282408d6d0f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('passwd', sa.VARCHAR(length=20), nullable=True),
    sa.Column('identity', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('suggestion')
    op.drop_table('goods_common')
    op.drop_table('card_info')
    op.drop_table('django_migrations')
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'department_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('department_number', mysql.INTEGER(display_width=10), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.create_table('django_migrations',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('app', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('applied', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('card_info',
    sa.Column('id', mysql.INTEGER(display_width=50), nullable=False),
    sa.Column('student_id', mysql.INTEGER(display_width=20), autoincrement=False, nullable=True),
    sa.Column('kinds', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('pay_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('pay_time', mysql.DATETIME(), nullable=True),
    sa.Column('money', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('left_money', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('goods_common',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('vardate', mysql.DATETIME(), nullable=True),
    sa.Column('linkman', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('contact', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('pulldate', mysql.DATETIME(), nullable=True),
    sa.Column('validdate', mysql.DATETIME(), nullable=True),
    sa.Column('haulway', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ps', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('websource', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('websourcelink', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('longterm', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('linkaddress', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('suggestion',
    sa.Column('id', mysql.INTEGER(display_width=50), nullable=False),
    sa.Column('student_id', mysql.INTEGER(display_width=20), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('mean', mysql.DOUBLE(precision=20, scale=0, asdecimal=True), nullable=True),
    sa.Column('amount', mysql.INTEGER(display_width=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('login')
    # ### end Alembic commands ###
